name: get_interfaces_in_workflow_ED29BAC5-7EE9-4035-B371-6E3BD770C213

label: List PAN-OS Logical interfaces

description: |
  This skillet demonstrates a simple REST api call to a PAN-OS NGFW to gather logical interfaces

type: rest

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  collection: Kitchen Sink

# Because this is being used in a workflow, we don't need to ask the user for these values again. However,
# a skillet can *only* access variables that are explicitly defined in the 'variables' section. To prevent the
# user from having to 'click' through another page, we can use the 'hidden' variable type to skip directly
# to applying this skillet
variables:
  - name: TARGET_IP
    description: Host
    default: 10.10.10.10
    type_hint: hidden
  - name: TARGET_PORT
    description: Port
    default: 443
    type_hint: hidden
  - name: TARGET_USERNAME
    description: Username
    default: admin
    type_hint: hidden
  - name: TARGET_PASSWORD
    description: Password
    default: admin
    type_hint: hidden

# Note you can combine multiple REST API calls by adding more 'snippet' sections. Any value captured in a previous
# step will immediately be available in the context for the next snippet as well. In this case, we capture 'api_key'
# then use it immediately in the next step.
snippets:
  - name: key_gen
    path: https://{{ TARGET_IP }}:{{ TARGET_PORT }}/api/?type=keygen&user={{ TARGET_USERNAME }}&password={{ TARGET_PASSWORD }}
    output_type: xml
    outputs:
      - name: api_key
        capture_pattern: result/key
  - name: get_interface_names
    path: https://{{ TARGET_IP }}/api/?type=op&cmd=<show><interface>logical</interface></show>&key={{ api_key }}
    output_type: xml
    outputs:
      - name: interface_names
        capture_pattern: ./result/ifnet/entry/name
