name: dynamic_ui_example-42CB-45DB-92E9-AD0753E44DE0
label: Template - Dynamic UI Example

description: |
  This skillet demonstrates how to use captured variabes to dynamically populate input controls.

type: template

labels:
  collection: Kitchen Sink

# Note the use of the 'source' attribute
variables:
  - name: selected_interface
    description: Interface
    default: not-saved
    type_hint: dropdown
    source: interface_names
  - name: interface_ips
    description: Interface IP Address For
    default: 10.10.10.10
    type_hint: text
    source: interface_names
  - name: radio_interface
    description: Interface By Radio
    default: not-saved
    type_hint: radio
    source: interface_names
  - name: checkbox_interface
    description: Interface by Checkbox
    default: not-saved
    type_hint: checkbox
    source: interface_names
  - name: hostname
    description: Hostname
    default: not-saved
    type_hint: hidden
  - name: uptime
    description: Uptime
    default: not-saved
    type_hint: hidden
  - name: sw_version
    description: Software Version
    default: not-saved
    type_hint: hidden


# Snippets is an ordered list of configuration xml fragments that will be pushed to the PAN-OS NGFW. The xpath
# determines where in the configuration hierarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: debug_output
    file: output.j2
    template_title: Dynamic UI Output
